### ISSUE TITLE
图片下载问题

### ISSUE THREAD

**Issue by JarvisFei** [AnnaYang2020/DeepEval#1]
这张图片始终无法下载
https://previews.agefotostock.com/previewimage/medibigoff/4a79bd13eeae0a2ed71352993cffc3ab/poh-dfs09a05_103.jpg

不知道能否提供一下？如果可以直接提供全部完整图片就更好了

**Comment by AnnaYang2020** [comment]
您好，感谢您对链接失效的反馈。这张图片如下：
![207](https://github.com/user-attachments/assets/d40de618-f570-4924-a953-7ab00d80eb8d)
