### ISSUE TITLE
文件data /Descripion_Questions.json，我猜，这个文件是不是Answer字段是不是错位了？

### ISSUE THREAD

**Issue by JarvisFei** [AnnaYang2020/DeepEval#2]
{"Image_ID": "Img743", "Url": "https://i.pinimg.com/236x/c5/15/b5/c515b5df4006cab56ffb3bd0325f525d.jpg", "Options": {"A": " There is a small house in the four pictures. In the first picture, a woman in a coat and holding a suitcase looks at the house and thinks about buying it. In the second picture, a man with a ladder looks at the small house and wants to paint it. In the third picture, a man in green clothes sees the small house and thinks about turning it into a restaurant. In the fourth picture, a child looks at the small house and thinks of a cozy small house.", "B": "There is a big tree in the four pictures. In the first picture, a man in a suit and holding a briefcase looks at the tree and thinks about making it into a wooden plank. In the second picture, a man with an ax looks at the big tree and wants to chop it down. In the third picture , a woman in red clothes sees the big tree and thinks about making it into furniture. In the fourth picture , a child looks at the big tree and thinks of a complete big tree.", "C": " There is a small rock in the four pictures. In the first picture, a woman in a dress and holding a purse looks at the rock and thinks about turning it into a paperweight. In the second picture, a man with a hammer looks at the small rock and wants to break it. In the third picture, a man in blue clothes sees the small rock and thinks about turning it into a sculpture. In the fourth picture, a child looks at the small rock and thinks of a shiny small rock.", "D": " There is a tiny flower in the four pictures. In the first picture, a woman in a hat and holding a basket looks at the flower and thinks about picking it. In the second picture, a man with a shovel looks at the tiny flower and wants to uproot it. In the third picture, a man in yellow clothes sees the tiny flower and thinks about turning it into a bouquet. In the fourth picture, a child looks at the tiny flower and thinks of a beautiful tiny flower."}, "Answer": "A", "Prompt_1": "Choose the correct answer to the following question. Which following text is the description of the image?\nOptions: (A) {} (B) {} (C) {} (D) {}\nAnswer:", "Prompt_2": "Select the appropriate description for the image from the options given. Which of these is the most suitable description for the image? \nChoices: A) {} B) {} C) {} D) {}\nCorrect Answer:", "Prompt_3": "Identify the most suitable description for the image from the given options. Which of the following should be chosen as the description? \nChoices are: A. {}, B. {}, C. {}, and D. {}. \nThe correct answer is:"}

以上面这道题为例，Answer看起来应该是选B，而不是选A

**Comment by JarvisFei** [comment]
[DeepSemantics_Questions.json](https://github.com/AnnaYang2020/DeepEval/blob/main/data/DeepSemantics_Questions.json), [Descripion_Questions.json](https://github.com/AnnaYang2020/DeepEval/blob/main/data/Descripion_Questions.json), and [Title_Questions.json](https://github.com/AnnaYang2020/DeepEval/blob/main/data/Title_Questions.json).

事实上，这三个文件的Answer字段，跟[Annotation.json](https://github.com/AnnaYang2020/DeepEval/blob/main/data/Annotation.json).文件相比，只有Title_Questions.json是完全正确的，另外两文件，存在很多对不上的地方，我看了一些case，Annotation.json文件的结果应该是对的，其他三个文件的Answer存在问题，希望可以纠正一下

**Comment by AnnaYang2020** [comment]
您好，我们在发布前最后调整发布数据的格式时，失误将Answer全部记为了A，感谢您的指出，目前已全部更正。

**Comment by JarvisFei** [comment]
谢谢你的更正。

**Comment by JarvisFei** [comment]
看了你的论文，有一个疑问，为什么deep semantics可以划分为论文中提到的六个类别？这个划分的由来有科学依据吗

**Comment by AnnaYang2020** [comment]
> 看了你的论文，有一个疑问，为什么deep semantics可以划分为论文中提到的六个类别？这个划分的由来有科学依据吗

您好，先前研究主要集中于讽刺图片或幽默图片，DeepEval数据集则覆盖了更多类别的图片。六个类别均是常见的图片种类，它们的定义可见附录D。

**Comment by JarvisFei** [comment]
附录D的定义，我有所疑惑
1. 疑惑一：这6种定义，似乎没有引用出处，如果是自己定义的，为何刚好是这6种定义。
2. 疑惑二：讽刺和幽默，讽刺和批判，有时候是共存的，这样的划分看起来似乎不是完全互斥。划分的依据是内容类型or表现手法？

**Comment by AnnaYang2020** [comment]
您好，

1. **这6种定义是通过参考既有研究，并结合我们在研究过程中对相关图片的详细分析总结归纳得出的。**

2. **我们主要基于图片的主要目的来进行分类。** 尽管从表现手法上看，这些属性在实践中往往会共存，但在图片的创作过程中，通常会有一个更为突出的侧重。例如：
   - 目的为幽默的图片：虽然可能带有讽刺的成分，但其主要目的是引发观众的笑声和娱乐。
   - 目的为讽刺的图片：虽然可能包含幽默元素，但其主要目的是通过讽刺、夸张等手法来揭露或批评某些社会现象或个人行为。
   - 目的为批判的图片：虽然图片中可能存在讽刺或幽默的元素，但其主要目的是通过理性分析对某个主题进行深入的评价或质疑，直接展现批判的问题。

**Comment by AnnaYang2020** [comment]
> 附录D的定义，我有所疑惑
> 
> 1. 疑惑一：这6种定义，似乎没有引用出处，如果是自己定义的，为何刚好是这6种定义。
> 2. 疑惑二：讽刺和幽默，讽刺和批判，有时候是共存的，这样的划分看起来似乎不是完全互斥。划分的依据是内容类型or表现手法？

您好，

1. **这6种定义是通过参考既有研究，并结合我们在研究过程中对相关图片的详细分析总结归纳得出的。**

2. **我们主要基于图片的主要目的来进行分类。** 尽管从表现手法上看，这些属性在实践中往往会共存，但在图片的创作过程中，通常会有一个更为突出的侧重。例如：
   - 目的为幽默的图片：虽然可能带有讽刺的成分，但其主要目的是引发观众的笑声和娱乐。
   - 目的为讽刺的图片：虽然可能包含幽默元素，但其主要目的是通过讽刺、夸张等手法来揭露或批评某些社会现象或个人行为。
   - 目的为批判的图片：虽然图片中可能存在讽刺或幽默的元素，但其主要目的是通过理性分析对某个主题进行深入的评价或质疑，直接展现批判的问题。
